import { useEffect,useMemo,useState } from "react";
import { Sidebar,TopBar } from "./DashboardPage";
import { getAnalytics } from "../api/resultApi";
import { BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,PieChart,Pie,Cell,LineChart,Line,Legend } from "recharts";
const P="Poppins, sans-serif",PRIMARY="#1565C0",ACCENT="#27ae60",MUTED="#4A6580",DARK="#0D2137";
const colors=[PRIMARY,ACCENT,"#7c3aed","#f57c00","#0097a7","#e53935"];
const card={background:"#fff",borderRadius:20,padding:24,border:"1px solid rgba(21,101,192,.08)",boxShadow:"0 2px 8px rgba(21,101,192,.06)"} as React.CSSProperties;
export default function ALPIDashboardPage(){const [data,setData]=useState<any>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");useEffect(()=>{getAnalytics().then(r=>setData(r.data)).catch(e=>setError(e?.response?.data?.message||"Unable to load analytics")).finally(()=>setLoading(false))},[]);const students=data?.studentProgress||[];const domain=data?.domainMastery||[];const activities=data?.activityDistribution||[];const timeline=data?.timeline||[];const avg=data?.avgAccuracy||0;const best=useMemo(()=>students.length?Math.max(...students.map((s:any)=>s.alpi)):0,[students]);return <div style={{display:"flex",height:"100vh",background:"#f4f7fb",fontFamily:P}}><Sidebar active="Analytics"/><div style={{flex:1,display:"flex",flexDirection:"column",overflow:"hidden"}}><TopBar title="Learning Analytics" subtitle="Live performance data from completed learning activities"/><main style={{flex:1,overflowY:"auto",padding:"28px 32px 40px"}}>{loading?<div style={{...card,textAlign:"center"}}>Loading live analytics…</div>:error?<div style={{...card,color:"#c62828"}}>{error}</div>:<>
<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:18,marginBottom:22}}>{[["Students",data.totalStudents,"people",PRIMARY],["Completed Activities",data.totalActivities,"sessions",ACCENT],["Average Accuracy",`${avg}%`,"all results","#7c3aed"],["Highest ALPI",best,"current learner mastery","#f57c00"]].map(([l,v,s,c]:any)=><div key={l} style={card}><div style={{fontSize:12,color:MUTED,fontWeight:700}}>{l}</div><div style={{fontSize:34,fontWeight:800,color:c,margin:"8px 0 3px"}}>{v}</div><div style={{fontSize:10,color:MUTED}}>{s}</div></div>)}</div>
<div style={{...card,marginBottom:22}}><div style={{fontSize:15,fontWeight:800,color:DARK,marginBottom:14}}>Student Progress</div><div style={{display:"flex",gap:14,overflowX:"auto"}}>{students.map((s:any,i:number)=><div key={s.id} style={{minWidth:170,border:"1px solid #e3edf7",borderRadius:16,padding:16,textAlign:"center"}}><div style={{fontWeight:800,color:DARK}}>{s.name}</div><div style={{fontSize:10,color:MUTED,margin:"4px 0 10px"}}>{s.learningLevel||"Beginner"} · {s.activities} activities</div><div style={{fontSize:30,fontWeight:800,color:colors[i%colors.length]}}>{s.alpi}</div><div style={{fontSize:10,color:MUTED}}>ALPI</div></div>)}</div></div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20,marginBottom:22}}><div style={card}><div style={{fontSize:14,fontWeight:800,color:DARK,marginBottom:12}}>Domain Mastery</div><ResponsiveContainer width="100%" height={280}><BarChart data={domain}><CartesianGrid strokeDasharray="3 3" stroke="#e8eef5"/><XAxis dataKey="domain" tick={{fontSize:10}}/><YAxis domain={[0,100]} tick={{fontSize:10}}/><Tooltip/><Bar dataKey="mastery" fill={PRIMARY} radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div><div style={card}><div style={{fontSize:14,fontWeight:800,color:DARK,marginBottom:12}}>Activity Distribution</div>{activities.length?<><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={activities} dataKey="value" nameKey="name" outerRadius={80} label><>{activities.map((_:any,i:number)=><Cell key={i} fill={colors[i%colors.length]}/>)}</></Pie><Tooltip/></PieChart></ResponsiveContainer><div style={{display:"flex",flexWrap:"wrap",gap:8}}>{activities.map((a:any,i:number)=><span key={a.name} style={{fontSize:10,color:MUTED}}>{a.name}: {a.value}</span>)}</div></>:<div style={{padding:40,textAlign:"center",color:MUTED}}>No completed activities yet.</div>}</div></div>
<div style={{...card,marginBottom:22}}><div style={{fontSize:14,fontWeight:800,color:DARK,marginBottom:12}}>Performance Timeline</div><ResponsiveContainer width="100%" height={260}><LineChart data={timeline}><CartesianGrid strokeDasharray="3 3" stroke="#e8eef5"/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis domain={[0,100]} tick={{fontSize:10}}/><Tooltip/><Legend/><Line type="monotone" dataKey="accuracy" name="Average Accuracy" stroke="#7c3aed" strokeWidth={3}/></LineChart></ResponsiveContainer></div>
<div style={card}><div style={{fontSize:14,fontWeight:800,color:DARK,marginBottom:14}}>Live Student Analytics</div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{["Student","Code","Activities","Accuracy","ALPI","Level"].map(h=><th key={h} style={{textAlign:"left",padding:10,color:MUTED,borderBottom:"1px solid #e7eef6"}}>{h}</th>)}</tr></thead><tbody>{students.map((s:any)=><tr key={s.id}><td style={{padding:10,fontWeight:700,color:DARK}}>{s.name}</td><td style={{padding:10}}>{s.studentCode}</td><td style={{padding:10}}>{s.activities}</td><td style={{padding:10}}>{s.accuracy}%</td><td style={{padding:10,fontWeight:800,color:PRIMARY}}>{s.alpi}</td><td style={{padding:10}}>{s.learningLevel||"Beginner"}</td></tr>)}</tbody></table></div></div>
</>}</main></div></div>}
