import { useEffect,useState } from "react";
import GameShell from "../components/GameShell";
import { saveResult } from "../api/resultApi";
const items=[{id:1,name:"🍎 Apple",category:"Fruits"},{id:2,name:"🍌 Banana",category:"Fruits"},{id:3,name:"🚗 Car",category:"Vehicles"},{id:4,name:"🚌 Bus",category:"Vehicles"},{id:5,name:"🐶 Dog",category:"Animals"},{id:6,name:"🐱 Cat",category:"Animals"}];const cats=["Fruits","Vehicles","Animals"];
export default function DragDropGame(){const [studentId,setStudentId]=useState("");const [remaining,setRemaining]=useState(items);const [score,setScore]=useState(0);const [time,setTime]=useState(60);const [done,setDone]=useState(false);const [wrong,setWrong]=useState<number|null>(null);
useEffect(()=>{if(done)return;if(time<=0){finish();return}const t=setInterval(()=>setTime(x=>x-1),1000);return()=>clearInterval(t)},[time,done]);
const finish=async()=>{if(done)return;setDone(true);const accuracy=Math.round(score/60*100);if(studentId)await saveResult({student:studentId,activityName:"Drag & Drop Sorting",moduleId:"game-drag-drop",domain:"Motor",level:"Beginner",totalQuestions:6,correctAnswers:score/10,wrongAnswers:6-score/10,score,accuracy,timeTaken:60-time,attempts:1,helpRequests:0}).catch(()=>{})};
const drop=(e:React.DragEvent,cat:string)=>{e.preventDefault();const id=Number(e.dataTransfer.getData("id"));const item=items.find(x=>x.id===id);if(!item)return;if(item.category===cat){setScore(x=>x+10);setRemaining(r=>{const n=r.filter(x=>x.id!==id);if(n.length===1)setTimeout(finish,0);return n})}else{setWrong(id);setTimeout(()=>setWrong(null),500)}};
if(done)return <GameShell title="Drag & Drop Sorting" icon="🧩" studentId={studentId} onStudentChange={setStudentId}><div style={st.result}><div style={{fontSize:62}}>🎉</div><h1>Excellent!</h1><p style={st.muted}>Final score: {score} / 60</p><button style={st.primary} onClick={()=>{setRemaining(items);setScore(0);setTime(60);setDone(false)}}>🔄 Play Again</button></div></GameShell>;
return <GameShell title="Drag & Drop Sorting" icon="🧩" studentId={studentId} onStudentChange={setStudentId} score={score} time={time} progress={score/60*100}><div style={st.card}><h2 style={st.h2}>Drag each item to the correct group</h2><div style={st.bins}>{cats.map(cat=><div key={cat} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,cat)} style={{...st.bin,borderColor:wrong&&items.find(x=>x.id===wrong)?.category!==cat?"#e53935":"#9fc1e5"}}><div style={st.binTitle}>{cat}</div><div style={st.binHint}>Drop items here</div></div>)}</div><div style={st.items}>{remaining.map(item=><div draggable onDragStart={e=>e.dataTransfer.setData("id",String(item.id))} key={item.id} style={st.item}>{item.name}</div>)}</div></div></GameShell>}
const st:any={card:{background:"#fff",borderRadius:22,padding:28,boxShadow:"0 4px 20px rgba(21,101,192,.08)"},h2:{textAlign:"center",color:"#0D2137",fontFamily:"Poppins",fontSize:18},bins:{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:16,margin:"24px 0"},bin:{minHeight:180,border:"2px dashed",borderRadius:18,background:"#F7FBFF",padding:18,textAlign:"center"},binTitle:{fontWeight:800,color:"#1565C0",fontSize:15},binHint:{fontSize:11,color:"#7A91A8",marginTop:8},items:{display:"flex",gap:12,justifyContent:"center",flexWrap:"wrap"},item:{padding:"14px 18px",background:"#fff",border:"1.5px solid #d5e2ef",borderRadius:14,fontWeight:700,cursor:"grab",boxShadow:"0 2px 8px rgba(21,101,192,.06)"},muted:{color:"#4A6580",fontSize:12},result:{background:"#fff",borderRadius:22,padding:40,textAlign:"center",boxShadow:"0 4px 20px rgba(21,101,192,.08)"},primary:{padding:"12px 22px",border:0,borderRadius:12,background:"#1565C0",color:"#fff",fontFamily:"Poppins",fontWeight:700,cursor:"pointer"}};
