import { useEffect, useState } from "react";
import GameShell from "../components/GameShell";
import { saveResult } from "../api/resultApi";
const original=["🍎","🍎","🐶","🐶","🚗","🚗","🌸","🌸","⭐","⭐","🐱","🐱"];
const shuffle=<T,>(a:T[])=>[...a].sort(()=>Math.random()-.5);
export default function MemoryGame(){const [studentId,setStudentId]=useState("");const [cards,setCards]=useState(shuffle(original));const [flipped,setFlipped]=useState<number[]>([]);const [matched,setMatched]=useState<number[]>([]);const [moves,setMoves]=useState(0);const [time,setTime]=useState(90);const [done,setDone]=useState(false);
useEffect(()=>{if(done)return;if(time<=0){finish();return}const t=setInterval(()=>setTime(x=>x-1),1000);return()=>clearInterval(t)},[time,done]);
useEffect(()=>{if(flipped.length!==2)return;setMoves(x=>x+1);const [a,b]=flipped;if(cards[a]===cards[b]){setMatched(x=>[...x,a,b]);setFlipped([])}else setTimeout(()=>setFlipped([]),650)},[flipped]);
useEffect(()=>{if(matched.length===cards.length&&cards.length)finish()},[matched]);
const finish=async()=>{if(done)return;setDone(true);const correct=matched.length/2;const total=cards.length/2;const accuracy=Math.round(correct/total*100);if(studentId)await saveResult({student:studentId,activityName:"Memory Matching",moduleId:"game-memory",domain:"Academic",level:"Beginner",totalQuestions:total,correctAnswers:correct,wrongAnswers:total-correct,score:accuracy,accuracy,timeTaken:90-time,attempts:1,helpRequests:0}).catch(()=>{})};
const restart=()=>{setCards(shuffle(original));setFlipped([]);setMatched([]);setMoves(0);setTime(90);setDone(false)};
if(done)return <GameShell title="Memory Matching" icon="🧠" studentId={studentId} onStudentChange={setStudentId}><div style={st.result}><div style={{fontSize:62}}>🧠🎉</div><h1>Memory Master!</h1><p style={st.muted}>Completed in {90-time}s with {moves} moves.</p><button style={st.primary} onClick={restart}>🔄 Play Again</button></div></GameShell>;
return <GameShell title="Memory Matching" icon="🧠" studentId={studentId} onStudentChange={setStudentId} score={matched.length/2} time={time} progress={matched.length/cards.length*100}><div style={st.card}><div style={st.grid}>{cards.map((c,idx)=>{const open=flipped.includes(idx)||matched.includes(idx);return <button key={idx} onClick={()=>{if(flipped.length<2&&!open)setFlipped(x=>[...x,idx])}} style={{...st.tile,background:open?"#fff":"#1565C0",color:open?"#0D2137":"#fff"}}>{open?c:"?"}</button>})}</div><p style={st.muted}>Find two matching pictures.</p></div></GameShell>}
const st:any={card:{background:"#fff",borderRadius:22,padding:28,boxShadow:"0 4px 20px rgba(21,101,192,.08)"},grid:{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14,maxWidth:680,margin:"0 auto"},tile:{height:110,borderRadius:18,border:"2px solid #dbe7f5",fontSize:42,cursor:"pointer",fontFamily:"Poppins",fontWeight:800},muted:{textAlign:"center",color:"#4A6580",fontSize:12,marginTop:18},result:{background:"#fff",borderRadius:22,padding:40,textAlign:"center",boxShadow:"0 4px 20px rgba(21,101,192,.08)"},primary:{padding:"12px 22px",border:0,borderRadius:12,background:"#1565C0",color:"#fff",fontFamily:"Poppins",fontWeight:700,cursor:"pointer"}};
