import { useState } from "react";
import GameShell from "../components/GameShell";
import { saveResult } from "../api/resultApi";

const questions=[{image:"🌳",answer:"Tree",options:["Tree","Rock","Flower","River"]},{image:"🐶",answer:"Dog",options:["Cat","Dog","Lion","Bird"]},{image:"🍎",answer:"Apple",options:["Banana","Apple","Orange","Mango"]},{image:"🚗",answer:"Car",options:["Bus","Train","Car","Bike"]},{image:"🌸",answer:"Flower",options:["Tree","Flower","Cloud","Sun"]}];
export default function PictureIdentificationGame(){const [studentId,setStudentId]=useState("");const [i,setI]=useState(0);const [score,setScore]=useState(0);const [selected,setSelected]=useState("");const [done,setDone]=useState(false);const q=questions[i];
const finish=async(finalScore:number)=>{setDone(true);if(studentId) await saveResult({student:studentId,activityName:"Picture Identification",moduleId:"game-picture-identification",domain:"Academic",level:"Beginner",totalQuestions:questions.length,correctAnswers:Math.round(finalScore/20),wrongAnswers:questions.length-Math.round(finalScore/20),score:finalScore,accuracy:Math.round((finalScore/(questions.length*20))*100),timeTaken:0,attempts:1,helpRequests:0}).catch(()=>{});};
const choose=(a:string)=>{if(selected)return;setSelected(a);const next=score+(a===q.answer?20:0);setScore(next);setTimeout(()=>{if(i===questions.length-1)finish(next);else{setI(x=>x+1);setSelected("")}},500)};
if(done)return <GameShell title="Picture Identification" icon="🖼️" studentId={studentId} onStudentChange={setStudentId}><div style={styles.result}><div style={{fontSize:64}}>🎉</div><h1 style={styles.h1}>Great Job!</h1><p style={styles.muted}>{studentId?"Learner completed the activity.":"Activity completed."}</p><div style={styles.scoreBox}>Final Score <strong>{score}</strong><span>{Math.round(score/(questions.length*20)*100)}% accuracy</span></div><button style={styles.primary} onClick={()=>{setI(0);setScore(0);setSelected("");setDone(false)}}>🔄 Play Again</button></div></GameShell>;
return <GameShell title="Picture Identification" icon="🖼️" studentId={studentId} onStudentChange={setStudentId} score={score} progress={(i/questions.length)*100}><div style={styles.card}><div style={styles.step}>QUESTION {i+1} / {questions.length}</div><h2 style={styles.h2}>What is this?</h2><div style={styles.image}>{q.image}</div><div style={styles.options}>{q.options.map(o=><button key={o} disabled={!!selected} onClick={()=>choose(o)} style={{...styles.option,...(selected&&o===q.answer?styles.correct:{}),...(selected===o&&o!==q.answer?styles.wrong:{})}}>{o}{selected&&o===q.answer?" ✓":""}</button>)}</div><p style={styles.muted}>Choose the correct picture name.</p></div></GameShell>}
const styles:any={card:{background:"#fff",borderRadius:22,padding:28,boxShadow:"0 4px 20px rgba(21,101,192,.08)",textAlign:"center"},step:{fontSize:11,fontWeight:800,color:"#1565C0",letterSpacing:1},h2:{fontFamily:"Poppins",color:"#0D2137",margin:"8px 0 18px"},image:{height:220,borderRadius:18,background:"#F6FAFF",display:"grid",placeItems:"center",fontSize:110,marginBottom:22},options:{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:12,maxWidth:600,margin:"0 auto"},option:{padding:"14px 18px",borderRadius:14,border:"1.5px solid #D7E1EA",background:"#fff",fontFamily:"Poppins",fontSize:14,fontWeight:700,cursor:"pointer"},correct:{background:"#E8F5E9",borderColor:"#27ae60",color:"#1b7a45"},wrong:{background:"#FFEBEE",borderColor:"#e53935",color:"#b71c1c"},muted:{color:"#4A6580",fontSize:12},result:{background:"#fff",borderRadius:22,padding:40,textAlign:"center",boxShadow:"0 4px 20px rgba(21,101,192,.08)"},h1:{color:"#0D2137"},scoreBox:{margin:"20px auto",padding:20,borderRadius:16,background:"#F0F6FF",display:"flex",flexDirection:"column",gap:8,fontSize:13,color:"#4A6580"},primary:{padding:"12px 22px",border:0,borderRadius:12,background:"#1565C0",color:"#fff",fontFamily:"Poppins",fontWeight:700,cursor:"pointer"}};
